language: node_js
node_js:
  - 0.10
before_install:
  - npm install -g npm@2.7.5
before_script:
  - npm install -g codeclimate-test-reporter
after_script:
  - codeclimate-test-reporter < test/coverage/**/lcov.info
